### ISSUE TITLE
Add Consul node metadata

### ISSUE THREAD

**Issue by f-minzoni** [automium/kubernetes#9]
The nodes listed in Consul can't be filtered easily by service version. Considering it's possible to associate arbitrary key/value pairs to the node during the registration process of the agent https://www.consul.io/docs/agent/options.html#_node_meta I think it's pretty straightforward to add the key "version" to the metadata.

**Comment by jsecchiero** [comment]
The configuration of consul is in the service-* side, would be nice to move this part in the provisioner.
At moment i have added this into [service-kubernetes](https://github.com/automium/service-kubernetes/blob/master/tasks/consul.yml#L137-L138) project
